### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/<APP-PACKAGE>/lib/arm/libandroid_platform.so" has bad ELF magic

### ISSUE THREAD

**Issue by amitks2015** [Azure-Samples/Cognitive-Speech-STT-Android#10]
Hi,

I am trying to integrate Bing Speech Recognizer with my app. But it looks like I am not able to find the appropriate JNI library libandroid_platform.so.
My project already contains arm64-v8a and armeabi-v7a under jniLibs. But [here](https://github.com/Microsoft/Cognitive-Speech-STT-Android/tree/master/SpeechSDK/libs) libandroid_platform.so is available for only x86 and armeabi. I get following exceptions:

> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.knowles.bali-1/lib/arm/libandroid_platform.so" has bad ELF magic
>                                                    at java.lang.Runtime.loadLibrary(Runtime.java:372)
>                                                    at java.lang.System.loadLibrary(System.java:1076)
>                                                    at com.microsoft.bing.speech.Conversation.<clinit>(Conversation.java:68)
>                                                    at com.microsoft.cognitiveservices.speechrecognition.SpeechRecognitionServiceFactory.createDataClient(SpeechRecognitionServiceFactory.java:147)
>                                                    at com.knowles.bali.bargein.BingVoiceService.initSpeechRecognition(BingVoiceService.java:61)

Can you please suggest what am I missing here?

>  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.knowles.bali-1/base.apk"],nativeLibraryDirectories=[/data/app/com.knowles.bali-1/lib/arm, /data/app/com.knowles.bali-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libandroid_platform.so"
>                                                        at java.lang.Runtime.loadLibrary(Runtime.java:367)
>                                                        at java.lang.System.loadLibrary(System.java:1076)
>                                                        at com.microsoft.bing.speech.Conversation.<clinit>(Conversation.java:68)
>                                                        at com.microsoft.cognitiveservices.speechrecognition.SpeechRecognitionServiceFactory.createDataClient(SpeechRecognitionServiceFactory.java:147)
>                                                        at com.knowles.bali.bargein.BingVoiceService.initSpeechRecognition(BingVoiceService.java:61)
>                                                        at com.knowles.bali.bargein.BingVoiceService.<init>(BingVoiceService.java:35)

Is it possible to get the .so file for other architectures as well?

**Comment by amitks2015** [comment]
There seems to be some problem with latest library 1.1.0. I am not getting any error with 0.6.0.

**Comment by brandall76** [comment]
I'm having a similar issue and having to use a workaround in my gradle file. It would be great if you could produce configurations for:

1. armeabi-v7a
2. arm64-v8a
3. x86_64
4. mips
5. mips64

**Comment by priyaravi20** [comment]
We currently only support for armeabi and x86.
