### ISSUE TITLE
onError  -1910505470

### ISSUE THREAD

**Issue by amitks2015** [Azure-Samples/Cognitive-Speech-STT-Android#11]
Any idea what's happening here? There is no issue with permission and network.

09-15 17:30:55.145 30615-31592/? I/NLPLAT: originating error 0x80070057
09-15 17:30:55.145 30615-31592/? I/NLPLAT: Authorization token hr 80070057 'S' 
09-15 17:30:55.147 30615-31592/? I/NLPLAT: originating error 0x80070057
09-15 17:30:55.147 30615-31592/? I/NLPLAT: originating error 0x80070057
09-15 17:30:55.148 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.148 30615-31592/? I/NLPLAT: Audio stream created
09-15 17:30:55.148 30615-31592/? I/NLPLAT: Adding requestId: 'S' for '8'
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Subscribing request [S]
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Audio Stream Created
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Creating transcoder 2
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Setting format for audio stream, 00000001
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.150 30615-31592/? I/NLPLAT: Sent first chunk of audio stream, requestId='84aa3f08-4341-30d1-ca1a-a634276ffaa6'
09-15 17:30:55.170 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.191 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.213 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.233 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.254 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.275 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.296 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.317 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.338 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: WebSocket closed unexpectedly, status: 0
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Closing web socket channel
09-15 17:30:55.356 30615-10021/? I/NLPLAT: CU Client connection dropped
09-15 17:30:55.356 30615-10021/? I/NLPLAT: ConnectionStateChanged
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Upgrade request returned with HTTP status code: 403.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Web socket handshake failed, hr=8E200002
09-15 17:30:55.356 30615-10021/? I/NLPLAT: web socket message delivery failed, hr=8E200002
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Web socket channel already closed.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Message: 'S' has -1712124788 remaining transmit attempts.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Retrying message, name='S'
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Initiating websocket connection. m_connection=0x9a050a74 host=websockets.platform.bing.com port=443
09-15 17:31:00.153 799-25738/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=21811837, 10.251.225.1, [24BE05F2A300], RTM_NEWNEIGH, NUD_REACHABLE}
09-15 17:31:09.103 799-25738/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=21820788, 10.251.225.1, [24BE05F2A300], RTM_NEWNEIGH, NUD_STALE}
09-15 17:31:10.357 30615-10021/? I/NLPLAT: originating error 0x80070057
09-15 17:31:10.357 30615-10021/? I/NLPLAT: Authorization token hr 80070057 'S' 
09-15 17:31:10.365 30615-10021/? I/NLPLAT: originating error 0x80070057
09-15 17:31:10.365 30615-10021/? I/NLPLAT: originating error 0x80070057
09-15 17:31:10.366 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.367 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.367 30615-10021/? I/NLPLAT: WSRequest
09-15 17:31:10.387 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.409 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.430 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.451 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.473 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.494 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.515 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.536 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.557 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.578 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.597 30615-10030/? I/NLPLAT: WebSocket closed unexpectedly, status: 0
09-15 17:31:10.597 30615-10030/? I/NLPLAT: Closing web socket channel
09-15 17:31:10.597 30615-10030/? I/NLPLAT: CU Client connection dropped
09-15 17:31:10.597 30615-10030/? I/NLPLAT: ConnectionStateChanged
09-15 17:31:10.597 30615-10030/? I/NLPLAT: Upgrade request returned with HTTP status code: 403.

**Comment by amitks2015** [comment]
There seems to be some problem with latest library 1.1.0. I am not getting any error with 0.6.0.

**Comment by myyyyf** [comment]
I also met this issue. Even though I rollback to the library 0.6.0, I still got the error "LoginFailed -1910505470". Anyone knows how to resolve it? I saw the last commit  was about "Android update with latest Cognitive Services auth". @jasonvomsft , is the auth of this service changed?

**Comment by amitks2015** [comment]
@myyyyf make sure to use correct api key 1 & 2.

**Comment by myyyyf** [comment]
[image: 内嵌图片 1]
This is the key I used. Is it right?


2016-10-14 15:50 GMT+08:00 amitks2015 <notifications@github.com>:

**Comment by myyyyf** [comment]
![image](https://cloud.githubusercontent.com/assets/10792393/19381498/67f2f32c-922e-11e6-8abf-2c5d69783d8d.png)
This is the key I used. Is it right? @amitks2015

**Comment by amitks2015** [comment]
That's correct. Are using both the keys as below?

`  dataClient =SpeechRecognitionServiceFactory.createDataClient(
                            (Activity)context,
                            SpeechRecognitionMode.ShortPhrase,
                            "en-us",
                            BingVoiceService.this,
                            primaryKey,
                            secondaryKey);`

**Comment by myyyyf** [comment]
Yes, I'm using both keys in file "SpeechRecoExample/res/values/strings.xml"
<string name="primaryKey">**********</string>
<string name="secondaryKey">*********</string>

**Comment by priyaravi20** [comment]
Closing this based on comment above of new auth endpoint.

**Comment by neoguo0601** [comment]
Get LoginFailed -1910505470 Reason just because the key is wrong?
I'm sure to use the correct Bing Speech api key, why still get this error?

**Comment by priyaravi20** [comment]
There might have been glitch with our auth server. Can u retest? I am able to successfully connect. Also, make sure your key is not expired.

**Comment by neoguo0601** [comment]
@priyaravi20 yes, I can use the key on windows sample,
but never succeeded on android sample
both Android 4.4.4 and 5.0.2,

**Comment by priyaravi20** [comment]
We have someone looking into this. Thanks for your patience.

**Comment by priyaravi20** [comment]
Android SDK has been updated today. Can you please retest and let us know your issue is fixed.

**Comment by tiro105** [comment]
Get login failed me too.
I use the key on windows sample.

environment
Android(Pixel2, Galaxy S8) 
Android Ver
Pixel2 Android 8.1
Galasy s8 Android 7.0
