### ISSUE TITLE
Callback functions of ISpeechRecognitionServerEvents can't be invoked under release version

### ISSUE THREAD

**Issue by xuangong** [Azure-Samples/Cognitive-Speech-STT-Android#16]
This library under Debug version works fine. But when I changed to release version, it doesn't work. There is no error in java level. And the callback functions of ISpeechRecognitionServerEvents can't be invoked anymore. Does it have any limitations when we use this library?

**Comment by jasonvomsft** [comment]
@xuangong is this due to your progaurd settings?

**Comment by priyaravi20** [comment]
CLosing due to no response from user.
