### ISSUE TITLE
WebSocket closed unexpectedly.  Web socket channel already closed.

### ISSUE THREAD

**Issue by mehul4795** [Azure-Samples/Cognitive-Speech-STT-Android#17]
When I am trying to send an audio file I am getting this error every-time.
Please help.

**Comment by jasonvomsft** [comment]
@mehul4795 can you send the error you are getting back?

**Comment by MHuangXin** [comment]
04-01 10:31:16.150 522-9386/com.microsoft.cognitive I/NLPLAT: Invalid argument 'messageType & 0'
04-01 10:31:16.150 522-9386/com.microsoft.cognitive I/NLPLAT: Failed to 'ParseMessage', HR=80070057
04-01 10:31:16.150 522-9386/com.microsoft.cognitive I/NLPLAT: Reporting connection failure to the observer (no pending messages yet).
04-01 10:31:16.150 522-9386/com.microsoft.cognitive I/NLPLAT: Transport error, hr=80070057
04-01 10:31:16.150 522-9386/com.microsoft.cognitive E/NLPLAT: native error -2147024809
04-01 10:31:16.150 522-9386/com.microsoft.cognitive E/VoiceEntryActivity: failure()
04-01 10:31:16.150 522-9386/com.microsoft.cognitive E/MicrosoftRecognize: onError------>: 
04-01 10:31:58.055 522-522/com.microsoft.cognitive I/NLPLAT: Create ImpressionId: 7b2ddb8107a682ea92f523965c4a509e
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: ImpressionId: S
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Adding requestId: 'S' for '2'
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Subscribing request [S]
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Audio stream created
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Adding requestId: 'S' for '6'
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Subscribing request [S]
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Audio Stream Created
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Creating transcoder 2
04-01 10:31:58.060 522-522/com.microsoft.cognitive I/NLPLAT: Sent first chunk of audio stream, requestId='654d090d-9fb5-881f-d4a6-294ec35bfe3c'
04-01 10:31:58.060 522-522/com.microsoft.cognitive W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: originating error 0x80004005
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: originating error 0x80004005
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: Failed to 'hresult', HR=80004005, WebSocket connection failed
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: No messages to retry, closing.
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: Closing web socket channel
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: CU Client connection dropped
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: ConnectionStateChanged
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: WebSocket closed unexpectedly, status: 0
04-01 10:31:58.105 522-9386/com.microsoft.cognitive I/NLPLAT: Web socket channel already closed.
04-01 10:31:58.140 522-522/com.microsoft.cognitive E/VoiceEntryActivity: start()
04-01 10:31:58.140 522-522/com.microsoft.cognitive E/MicrosoftRecognize: onAudioEvent------>: 
04-01 10:31:58.365 522-10760/com.microsoft.cognitive I/NLPLAT: Initiating websocket connection. m_connection=0x7b5e6724 host=websockets.platform.bing.com port=443
04-01 10:31:58.365 522-10760/com.microsoft.cognitive I/NLPLAT: WSRequest
04-01 10:31:58.365 522-10760/com.microsoft.cognitive I/NLPLAT: Authorization token hr 0 'S' 
04-01 10:31:58.365 522-10760/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.450 522-10760/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.565 522-10760/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.645 522-10760/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.745 522-10760/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.865 522-10760/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.960 522-522/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.960 522-522/com.microsoft.cognitive I/NLPLAT: Sending audio stream endpoint, requestId='S'
04-01 10:31:58.960 522-522/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:58.960 522-522/com.microsoft.cognitive I/NLPLAT: Sent audio stream endpoint, requestId='S'
04-01 10:31:58.990 522-522/com.microsoft.cognitive I/NLPLAT: signaling OnAudioEvent(AUDIO_EVENT_RECORD_STOP)
04-01 10:31:58.990 522-522/com.microsoft.cognitive E/VoiceEntryActivity: complete()
04-01 10:31:58.990 522-522/com.microsoft.cognitive E/MicrosoftRecognize: onAudioEvent------>: 
04-01 10:31:58.990 522-522/com.microsoft.cognitive D/MicrosoftRecognize: invok stop to end Mic--->
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: Upgrade request returned with HTTP status code: 101.
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: Web socket handshake completed
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: CU Client connected
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: Adding requestId: 'S' for '6'
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: Subscribing request [S]
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: Waiting for connection/send completion.
04-01 10:31:59.095 522-10765/com.microsoft.cognitive I/NLPLAT: ConnectionStateChanged

**Comment by priyaravi20** [comment]
We are currently investigating this issue.

**Comment by priyaravi20** [comment]
This has been fixed. Please retry.
