### ISSUE TITLE
Platform library has text relocations

### ISSUE THREAD

**Issue by gcampax** [Azure-Samples/Cognitive-Speech-STT-Android#22]
And thus cannot be loaded in Android 7 or above, which are more strict than before about it, if used in an app compiled for Android 6 or above.

**Comment by Spring8848** [comment]
it doesn't support Android 6 yet,finally 5.1 passed

**Comment by gcampax** [comment]
It does support Android 6, just not Android 7. To be more clear:

- if you compile your app for 5.1 or less (targetSdkVersion <= 22), it will work on any device, including Android 7
- if you compile your app for 6 (= 23), it will work on Android 6, but not Android 7 (API 24) or 7.1 (API 25)

Specifically, you get a popup warning on arm, and an outright crash on x86.

**Comment by Spring8848** [comment]
hi,gcampax
do you know how to keep MicrophoneRecognitionClient running and recognizing status unless i close micphone by myself?
The  MicrophoneRecognitionClient will endMicAndRecognition after about 55 seconds on ShortPhase mode (tested by myself) even though i am still  speaking continuously.

thank you !

**Comment by gcampax** [comment]
I'm sorry, I don't know about that. It might be a limitation on the API (after 55 seconds the phrase is not short anymore)

**Comment by priyaravi20** [comment]
Please use Long Mode for any audio greater than 15 seconds.
