### ISSUE TITLE
How can I increase reading audio file and its speech recognition performance?

### ISSUE THREAD

**Issue by YYurtcan** [Azure-Samples/Cognitive-Speech-STT-Android#23]
Hi,
First of all, this is good example. Thank you to Microsoft. I am using it for my project. However, reading audio file and its speech recognition takes time and it is not working in the real time.  On the other by using microphone mode, it is working almost real time. What steps I should follow in order to decrease reading audio file and its speech recognition time?
Best regards.

**Comment by priyaravi20** [comment]
Speech recognition results are sent back at the audio rate not at the transmission rate . Microphone audio and transmission rate are very close and hence latency is not observed by you.
