### ISSUE TITLE
onIntentReceived method is not being called when I select "Use Microphone and intent detection" mode

### ISSUE THREAD

**Issue by WksKing** [Azure-Samples/Cognitive-Speech-STT-Android#24]
for some reason, the method "OnIntentReceived" is not being called, but "onFinalResponseReceived" method is called, I just using this demo to test, and I have replaced "primaryKey", "luisAppID", "luisSubscriptionID" resource in strings.xml file. 
please help.

**Comment by antero10** [comment]
I'm facing with the same problem using `android 7`,  is a problem with the `android`  version?.

**Comment by kaiomagalhaes** [comment]
Same here @WksKing, which version of android are you using?

**Comment by WksKing** [comment]
@kaiomagalhaes Marshmallow!

**Comment by kaiomagalhaes** [comment]
@jasonvomsft  any idea? ^

**Comment by priyaravi20** [comment]
Your steps seems correct. Can you provide logs to debug further.

**Comment by simon-koehler** [comment]
I am facing the same problem on an AVD Pixel Phone API 23
My logs:
logcat: https://pastebin.com/mgF92PaV
In-App: https://pastebin.com/mYXU4pJu

**Comment by chenxin21cn** [comment]
I found only West Us region's LUIS key can get LUIS intent response.

**Comment by priyaravi20** [comment]
Yes. LUIS is still in preview and not a global service yet.

**Comment by kaiomagalhaes** [comment]
Just wondering, was it solver @priyaravi20 ?

**Comment by priyaravi20** [comment]
We updated the SDK couple of months back. Please retest and we have more fixes planned for next month as well.

**Comment by kaiomagalhaes** [comment]
awesome! thanks!

**Comment by Rootnotfound** [comment]
Still having this problem
