### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by lsc4719** [Azure-Samples/Cognitive-Speech-STT-Android#25]
Build the sample  First, you must obtain a Bing Speech API subscription key by following the instructions on our website.  Start Android Studio and choose "Import project (Eclipse ADT, Gradle, etc.)" from the "Quick Start" options from Speech > SpeechToText > Android folder.

"Speech > SpeechToText > Android" path seems wrong.

Because there is no folder "Speech".

**Comment by priyaravi20** [comment]
Please follow steps under https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedjavaandroid
