### ISSUE TITLE
How to support armeabi，armeabi-v7a，x86，mips，arm64-v8a，mips64，x86_64。

### ISSUE THREAD

**Issue by MHuangXin** [Azure-Samples/Cognitive-Speech-STT-Android#26]
My app use microsoft speech with third party SDK,but the "third party SDK" support armeabi，armeabi-v7a，x86，mips，arm64-v8a，mips64，x86_64。so should I delete them?only keep armeabi,x86;

Microsoft can not supported the major platforms  well,it‘’s base ability for solution provider.
I see several issues about this problem.but no answer for these issues.
okay. no way I have to give up Microsoft .

**Comment by hatsunea** [comment]
I also need to provide armeabi, armeabi-v7a，x86，arm64-v8a.
If it is difficult to create at Microsoft, consider open sourcing.

**Comment by MHuangXin** [comment]
u can try to use google

**Comment by hatsunea** [comment]
google dont suppert streaming recognition.

**Comment by MHuangXin** [comment]
houndify

**Comment by priyaravi20** [comment]
Sorry about your experience. We are planning to release the protocol documentation so users can write their own platform implementation. Please stay tuned.

Thanks
Priya Rajan
