### ISSUE TITLE
Leaking at OpenSLES level?

### ISSUE THREAD

**Issue by magicseth** [Azure-Samples/Cognitive-Speech-STT-Android#27]
If I try to transcribe a bunch of times (about 15) it stops working. I am calling start and endMicAndRecognition manually.

I/NLPLAT: Subscribing request [S]
I/NLPLAT: Audio Stream Created
I/NLPLAT: Creating transcoder 2
I/NLPLAT: Waiting for connection/send completion.
I/NLPLAT: Sent first chunk of audio stream, requestId='48724639-d195-7dcb-c0c
E/libOpenSLES: Too many objects
W/libOpenSLES: Leaving Engine::CreateAudioRecorder (SL_RESULT_MEMORY_FAILURE)
E/NLPLAT: native error -2147418113
D/SPEECH: --- Error received by onError() ---
D/SPEECH: Error code: Unknown -2147418113
D/SPEECH: Error text: 
I/NLPLAT: originating error 0x8000ffff
I/NLPLAT: originating error 0x8000ffff
 I/NLPLAT: Upgrade request returned with HTTP status code: 101.
 I/NLPLAT: Web socket handshake completed
 I/NLPLAT: CU Client connected
 I/NLPLAT: ConnectionStateChanged
I/NLPLAT: Invalid argument 'messageType & 0'
I/NLPLAT: Failed to 'ParseMessage', HR=80070057
I/NLPLAT: Reporting connection failure to the observer (no pending messages y
I/NLPLAT: Transport error, hr=80070057
E/NLPLAT: native error -2147024809
D/SPEECH: --- Error received by onError() ---
D/SPEECH: Error code: InvalidArgument -2147024809
D/SPEECH: Error text: 
I/NLPLAT: Invalid argument 'messageType & 0'
I/NLPLAT: Failed to 'ParseMessage', HR=80070057
I/NLPLAT: Reporting connection failure to the observer (no pending messages y
I/NLPLAT: Transport error, hr=80070057
E/NLPLAT: native error -2147024809
D/SPEECH: --- Error received by onError() ---
D/SPEECH: Error code: InvalidArgument -2147024809

**Comment by priyaravi20** [comment]
We are currently investigating this issue.

**Comment by priyaravi20** [comment]
CLosing old issue. Please retry with latest update of SDK with bug fixes and stability improvements.
