### ISSUE TITLE
Probabilistic “ANR” when invok metho “startMicAndRecognition”

### ISSUE THREAD

**Issue by MHuangXin** [Azure-Samples/Cognitive-Speech-STT-Android#28]
![qq 20170401101125](https://cloud.githubusercontent.com/assets/15179354/24574351/d4d23f56-16c3-11e7-9ac3-1b821735acb5.png)

**Comment by MHuangXin** [comment]
i think sometimes WebSocket create a new connection spend a long time.it cause app throw anr exception.so how can i fix this problem

**Comment by MHuangXin** [comment]
@jasonvomsft it often occured when the network is slow

**Comment by priyaravi20** [comment]
We are currently trying to reprduce this issue. Can you send us exact repro steps?

Thanks
Priya Rajan

**Comment by priyaravi20** [comment]
CLosing old issue. Please retry with latest update of SDK with bug fixes and stability improvements.
