### ISSUE TITLE
native error

### ISSUE THREAD

**Issue by MHuangXin** [Azure-Samples/Cognitive-Speech-STT-Android#29]
04-01 10:17:52.664 19668-17589/com.microsoft.cognitive I/NLPLAT: Invalid argument 'messageType & 0'
04-01 10:17:52.664 19668-17589/com.microsoft.cognitive I/NLPLAT: Failed to 'ParseMessage', HR=80070057
04-01 10:17:52.664 19668-17589/com.microsoft.cognitive I/NLPLAT: Reporting connection failure to the observer (no pending messages yet).
04-01 10:17:52.664 19668-17589/com.microsoft.cognitive I/NLPLAT: Transport error, hr=80070057
04-01 10:17:52.665 19668-17589/com.microsoft.cognitive E/NLPLAT: native error -2147024809

**Comment by MHuangXin** [comment]
when this error occurred.speech recognize sdk doesn't work anymore until I kill Application process and restart Application .

**Comment by iyotetsuya** [comment]
I have same error here, Is there any solution, workaround or suggestion to this issue?

**Comment by iyotetsuya** [comment]
@MHuangXin 
it seems to timeout from server,
you can try to init `MicrophoneRecognitionClient` again, instead of restarting app.

**Comment by MHuangXin** [comment]
@iyotetsuya it often occur when network is slow.but In this case we cant ge any callback or exception.so I should init MicrophoneRecognitionClient again for every recognization?I try to init new client every time.but it doesn't work.sometime time out can make app throw ANR exception.

**Comment by iyotetsuya** [comment]
@MHuangXin 
I get callback from `ISpeechRecognitionServerEvents.onError(int errorCode, String response)`
and init it again when error code is `-2147024809`

**Comment by MHuangXin** [comment]
@iyotetsuya ok thanks

**Comment by priyaravi20** [comment]
We are currently investigating this issue. Please send complete logs to debug this further.

**Comment by priyaravi20** [comment]
CLosing old issue. Please retry with latest update of SDK with bug fixes and stability improvements.

**Comment by lostsearover** [comment]
This issue doesn't been fixed. Do you test it?

**Comment by Licantrop0** [comment]
@priyaravi20 we are still hitting the issue with the Android SDK

**Comment by BeanStalka** [comment]
I am also hitting this issue with the 'new' SDK

**Comment by BeanStalka** [comment]
I need a fix for this ASAP or I will have to rip Bing out of my project

**Comment by wolfma61** [comment]
@Beanstalka - we haven't released an Android version of the new SDK yet. 

see here: https://azure.microsoft.com/en-us/blog/speech-services-now-in-preview/

If you have a similar issue there, pls post an issue on Stackoverflow as hinted in the blog-post
