### ISSUE TITLE
user android class MediaRecorder  AudioRecord: start() status -38

### ISSUE THREAD

**Issue by androidjiawei** [Azure-Samples/Cognitive-Speech-STT-Android#30]
when i used MediaRecorder.start(), 
throws java.lang.IllegalStateException android.media.MediaRecorder.native_start(Native Method)
AudioRecord: start() status -38
 i  want to user MediaRecorder for mMediaRecorder.getMaxAmplitude()
i used MediaRecorder to getVolume for  anytime,
 it seems to conflict with micsoft,
thanks

**Comment by priyaravi20** [comment]
We do not support concurrent microphone usage.
