### ISSUE TITLE
SpeechSDK.jar missing

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#33]
I cant seem to find a file referenced in the documentation.  

"Using files downloaded from the speech_SpeechToText-SDK-Android zip package, do the following:
Copy the **speechsdk.jar** file, found in the SpeechSDK folder inside the Bin folder, to the “your-application\app\libs” folder."

I will give it a go with the old file from the deprecated repo, but its about a year old so I'm pretty sure that's just asking for trouble.

**Comment by Danieladu** [comment]
Met the same thing.

**Comment by priyaravi20** [comment]
Hi - This jar file is part of the gradle package. If you import the file you should see this in the specified folder.
