### ISSUE TITLE
No 64 bit version of libandroid_platform.so native library

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#34]
I'm using Xamarin and using a bound library to leverage the Bing Speech Recognition API
Since I have other NuGet packages that use 64 bit versions, I also need a 64 bit version of the  libandroid_platform.so.

This is a blocker and if I cannot find away around this soon, we will have to look at other technologies for our STT needs.

**Comment by priyaravi20** [comment]
Hi - We recently released the protocol documentation so developers can write their platform/language dependent implementation. More info here : https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/websocketprotocol.
Hope that helps.
