### ISSUE TITLE
Continuous recognition

### ISSUE THREAD

**Issue by bjaanes** [Azure-Samples/Cognitive-Speech-STT-Android#35]
Hi, I am trying to implement continuous recognition (using SpeechRecognitionMode.LongDictation)., but the microphone client seems to shut down after a while (at least there is nothing happening that I can see). Is there any way to know when this happens so I can automatically restart it?

**Comment by bjaanes** [comment]
It seems like this might be a bug in the SDK. I also see this happening in the test app. If you choose long dictation, the audio shuts down after about 2 minutes, but there is no event for it (audioChanged).

**Comment by priyaravi20** [comment]
We only support 2 min of audio for 1 call. If you would like to send longer audio my suggestion would be to use our new API and implement an android version for your scenario. Documentation can be found here : https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/websocketprotocol

**Comment by bjaanes** [comment]
But you have to recognize that implementing that is not really what I want to do, I just want to use a good easy-to-use SDK :)

The problem is not the 2 min limit, but the fact that no audioEvent is raised when it stops. It does so with the other ones, but not for long dictation.
