### ISSUE TITLE
StartMicAndRecognition takes a long time (.8 - 1 secs) before listening.

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#37]
I am initializing as much as I can in the on create.

When I call StartMicAndRecognition it takes an average of .8 seconds to start listening.

This seems to be a long time to wait to be able to speak, and will not work in my implementation.

I am using Xamarin and I am using a Bound Library for  Bing SR SDK.  I could not find a NuGet Package.

attached please find my implementation.

Any suggestions you may have to limit the time it takes to listen would be greatly appreciated.

Thanks,

Andrew Glatts

[BingSpeechToTextEngine.txt](https://github.com/Azure-Samples/Cognitive-Speech-STT-Android/files/1025584/BingSpeechToTextEngine.txt)

**Comment by priyaravi20** [comment]
Hi Andrew - Have you used the samples already available(C# one) to see if you experience the same latency. We are not observing any service level latencies and about 400 ms latency is expected.

**Comment by BeanStalka** [comment]
No I have not.  My application is Xamarin Android. 

I was able to get the times down to about .5 or .6.  

I now have a bigger problem though.  I opened another issue about it.

It seems I cannot use the _microphoneRecognitionClient twice without an error occurring.  The second time around it always fails
