### ISSUE TITLE
DataRecognitionClient.EndAudio() takes over 5 seconds to return result

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#39]
I have a byte array of PCM audio data.

I loop through it grabbing 1024 bytes at a time calling 

DataRecognitionClient.SendAudio(arraySlice, length);

After all the looping is done, I call

DataRecognitionClient.EndAudio();

Then I wait, for an average of 5 seconds. before final results is called with the results.

I have many questions:

1.) Is there anything I can do to speed up this response, as it is now its basically unusable.  5 seconds is an eternity for someone to wait for voice recognition.  Maybe formatting the file in another way??

2.) Is this response time expected?  (I hope not)

3.) What is the maximum amount of audio data I can send up via SendAudio or EndAudio?  maybe I can increase the buffers

Any help you could provide would be greatly appreciated.

Thanks

**Comment by BeanStalka** [comment]
UPDATE Looping was the issue

I am sending all the data at once and there is a very fast response (.4 seconds).

I still need to know what the max amount of data to send in one shot is, or if the SDK takes care of parsing it.

**Comment by priyaravi20** [comment]
There isn't a data limit on the SDK side. There is a audio limit of 2 mins if you are using this android SDK.
