### ISSUE TITLE
Cannot find a way to add to the Bing Dictionary

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#41]
I have an android app that uses pocketsphinx for wake word detection, then hands off the raw audio data to the Bing SR DataRecognitionClient. 

I would like to re verify that the wake phrase has been said and remove it from the resultant string from the DataRecognitionClient.

For arguments sake, lets say my phrase is  "OK Flarpy"

How do I let Bing know that "Flarpy"  is the word I am saying instead of letting it guess all sorts of close sounding words.  IOW how do I add Flarpy to the dictionary?

I'm sure there is a way to supply additional words, I just can't find it.

**Comment by priyaravi20** [comment]
We donot have this currently supported. But we do plan to able to add this in the future.
