### ISSUE TITLE
MicrophoneRecognitionClient fails the second time.

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#43]
I am using BING MicrophoneRecogntionClient.StartMicAndRecogntion() to capture the users voice.

It works the first time around, but the second time if fails with this error.

I just started to see this issue on 6/2/2107

Here is the error:
06-05 08:48:57.700 W/System.err( 3206): java.lang.Exception
06-05 08:48:57.704 W/System.err( 3206): 	at com.microsoft.cognitiveservices.speechrecognition.Contract.fail(Contract.java:23)
06-05 08:48:57.704 W/System.err( 3206): 	at com.microsoft.cognitiveservices.speechrecognition.Contract.requires(Contract.java:47)
06-05 08:48:57.704 W/System.err( 3206): 	at com.microsoft.cognitiveservices.speechrecognition.MicrophoneRecognitionClient.startMicAndRecognition(MicrophoneRecognitionClient.java:52)
06-05 08:48:57.704 W/System.err( 3206): 	at md55616150122aa999b164cbaec3db3fe56.AthenaUtteranceProgressListener.n_onDone(Native Method)
06-05 08:48:57.705 W/System.err( 3206): 	at md55616150122aa999b164cbaec3db3fe56.AthenaUtteranceProgressListener.onDone(AthenaUtteranceProgressListener.java:38)
06-05 08:48:57.705 W/System.err( 3206): 	at android.speech.tts.TextToSpeech$Connection$1.onSuccess(TextToSpeech.java:2118)
06-05 08:48:57.706 W/System.err( 3206): 	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:63)
06-05 08:48:57.706 W/System.err( 3206): 	at android.os.Binder.execTransact(Binder.java:565)

**Comment by BeanStalka** [comment]
Any progress on this issue?  It is still occurring every second time

**Comment by priyaravi20** [comment]
Can you send the exact repro steps using the sample. There has been no updates to the client recently and want to understand better.

**Comment by BeanStalka** [comment]
1.) SpeechRecognitionServiceFactory.CreateMicrophoneClient()
2.)  _microphoneRecognitionClient?.StartMicAndRecognition();
3.) _microphoneRecognitionClient?.EndMicAndRecognition();
4.) First time works
5.) Seconds later, _microphoneRecognitionClient?.StartMicAndRecognition();
6.) ERROR: See above (com.microsoft.cognitiveservices.speechrecognition.Contract.requires(Contract.java:47))

**Comment by priyaravi20** [comment]
Thanks for your patience on this issue. We tested the steps and works fine on our end. The issue might be caused by calling Start again without End being called.
Are you setting _microphoneRecognitionClient to null before EndMicAndRecognition() is called?  We suspect this might be the issue. We will also make the code more resilient by calling EndMicAndRecognition() if m_Initialized is already true when calling StartMicAndRecognition(), instead of just failing with a Contract exception in the next version.

**Comment by BeanStalka** [comment]
No I am not nulling out the object before calling EndMicAndRecognition

I create the instance in my constructor

then I use it once.

then I use it a second time and it fails.

I think you are not seeing this behavior because the sample app that you supply has the clients initialized before each use.

This is obscuring the issue from you.  Try to initilize the clients Once OnCreate in your activity, Then use that client multiple times.

It will fall over on the second use like clock work

Re-initilizing for every use is not acceptable because the time it takes to do this adds to the response time of the voice recognition.  

We need that as fast as possible.

Please retest, initializing once and using twice and let me know what you get.

Thanks

**Comment by priyaravi20** [comment]
We have updated the Android SDK which has a few bug fixes. Please retest with latest and lets us know if that helped resolve your issues. Thanks.

**Comment by priyaravi20** [comment]
Hi BeanStalka - Please update this thread if the new SDK resolves your issues so I can close the thread. Thanks!

**Comment by BeanStalka** [comment]
Turns out that After The OnFInalResult is raised, I need to call EndMicAndREcognition

Once I did that I was able to get it to work with one initialization.
