### ISSUE TITLE
MicrophoneRecognitionClient - RecognitionStatus of 201 - Cancel.  No Documentation available for these statuses

### ISSUE THREAD

**Issue by BeanStalka** [Azure-Samples/Cognitive-Speech-STT-Android#44]
When using the MicrophoneRecognitionClient , I receive a  RecognitionStatus of 201 - Cancel

I could not find any documentation on what this error means.

Can you please point me at some documentation that explains this and the other statuses?

**Comment by priyaravi20** [comment]
This response means User has cancelled the recognition.  Here are the codes : 

 contains an intermediate result - 100
 a recognition result was found -  200
 no result was found - 301
 initial silence in the audio exceeded the maximum  -  303
 timeout period exceeded for background noise -   304
 maximum time reached for hot word recognition - 305
 recognition was canceled by the client  -  201
 there was an error during recognition  -  500
 end of dictation silence timeout -   610
 in dictation mode, the server is truly done  - 612
