### ISSUE TITLE
always LoginFailed -1910505470? I'm sure to use the correct Bing Speech api key

### ISSUE THREAD

**Issue by neoguo0601** [Azure-Samples/Cognitive-Speech-STT-Android#45]
Get LoginFailed -1910505470 Reason just because the key is wrong?
I'm sure to use the correct Bing Speech api key, why still get this error?

**Comment by neoguo0601** [comment]
I use that kay can run with Windows sample

**Comment by priyaravi20** [comment]
We are looking into this and plan to release a new version with updates this week.

**Comment by neoguo0601** [comment]
That's great, in the new version I ran the sample successfully. thanks @priyaravi20

**Comment by neoguo0601** [comment]
@priyaravi20 I know why I always get login failed, 

    
    <string name="authenticationUri"></string>

I filled the URL into authenticationUri, it becomes the following:

    
    <string name="authenticationUri">https://westus.api.cognitive.microsoft.com/sts/v1.0/issuetoken</string>

Even if I fill out the URL, I think it should not be wrong, but I can work now, or very thank you

**Comment by yatindra27** [comment]
I'm seeing the same issue even after adding proper Authentication URI.

**Comment by yatindra27** [comment]
I see following error:
--- Microphone status change received by onAudioEvent() ---
********* Microphone status: true *********
Please start speaking.
--- Error received by onError() ---
Error code: LoginFailed -1910505470
Error text: 

--- Microphone status change received by onAudioEvent() ---
********* Microphone status: false *********


--- Start speech recognition using microphone with ShortPhrase mode in en-us language ----

**Comment by yatindra27** [comment]
After changing URI to https://api.cognitive.microsoft.com/sts/v1.0/issuetoken; it started working.

**Comment by radhasoni65** [comment]
Hey 
i had done all the steps but still not able to login get the same error.
please help me...
