### ISSUE TITLE
Sample cannot recognize audio in ShortPhrase (microphone) when user tap Start button before closing Websocket

### ISSUE THREAD

**Issue by nkgami** [Azure-Samples/Cognitive-Speech-STT-Android#56]
## Issue Description
I'm trying Bing Speech to Text sample for Android.  I have a problem in ShortPhrase mode (microphone). 1st time, the app can recognize from microphone audio, but 2nd time the app cannot recognize.

## Repro Steps
(1) Start sample application
(2) Select "Use Microphone with ShortPhrase mode" radio button
(3) Tap Start button
(4) Input some voice from microphone
(5) Shortly after recognition (when start button is enabled), tap Start button again
(6) Input some voice from microphone
(7) No recognition event occurs

On step (5), if the user waits until the websocket closing (when the following debug logs are shown) before tap Start button, this problem does not happen.

```
9-21 21:45:03.257 14361-17913/com.microsoft.CognitiveServicesExample I/NLPLAT: No messages to retry, closing.
09-21 21:45:03.257 14361-17913/com.microsoft.CognitiveServicesExample I/NLPLAT: Closing web socket channel
09-21 21:45:03.258 14361-17913/com.microsoft.CognitiveServicesExample I/NLPLAT: CU Client connection dropped
09-21 21:45:03.258 14361-17913/com.microsoft.CognitiveServicesExample I/NLPLAT: ConnectionStateChanged
09-21 21:45:03.258 14361-17913/com.microsoft.CognitiveServicesExample I/NLPLAT: WebSocket closed unexpectedly, status: 0
09-21 21:45:03.258 14361-17913/com.microsoft.CognitiveServicesExample I/NLPLAT: Web socket channel already closed.
```

## Work around
I found a work around for this problem. If micClient is reset (finalized) before tap Start button, this problem does not occur. Workaround code is like below.

```
public void onFinalResponseReceived(final RecognitionResult response) {
boolean isFinalDicationMessage = this.getMode() == SpeechRecognitionMode.LongDictation &&
            (response.RecognitionStatus == RecognitionStatus.EndOfDictation ||
                    response.RecognitionStatus == RecognitionStatus.DictationEndSilenceTimeout);
if (null != this.micClient && this.getUseMicrophone() && ((this.getMode() == SpeechRecognitionMode.ShortPhrase) || isFinalDicationMessage)) {
// we got the final result, so it we can end the mic reco.  No need to do this
        // for dataReco, since we already called endAudio() on it as soon as we were done
        // sending all the data.
        this.micClient.endMicAndRecognition();
//** Work around start here **//
        // Reset micClient
        if (this.micClient != null) {
this.micClient.endMicAndRecognition();
try {
this.micClient.finalize();
            } catch (Throwable throwable) {
                throwable.printStackTrace();
            }
this.micClient = null;
        }
this._startButton.setEnabled(true);
//** End of work around **//
    }

if (isFinalDicationMessage) {
this._startButton.setEnabled(true);
this.isReceivedResponse = FinalResponseStatus.OK;
    }

if (!isFinalDicationMessage) {
this.WriteLine("********* Final n-BEST Results *********");
for (int i = 0; i < response.Results.length; i++) {
this.WriteLine("[" + i + "]" + " Confidence=" + response.Results[i].Confidence +
" Text=\"" + response.Results[i].DisplayText + "\"");
        }

this.WriteLine();
    }
}
<snipped>
public void onAudioEvent(boolean recording) {
    this.WriteLine("--- Microphone status change received by onAudioEvent() ---");
    this.WriteLine("********* Microphone status: " + recording + " *********");
    if (recording) {
        this.WriteLine("Please start speaking.");
    }

    WriteLine();
    if (!recording) {
        this.micClient.endMicAndRecognition();
        //** comment out **//
        //this._startButton.setEnabled(true);
    }
}
```

I think this is a problem of library because I call endMicAndRecognition method before calling startMicAndRecognition but the library seems to fail to handle websocket connection correctly.

**Comment by raaaar** [comment]
Your trace looks to be more than a week old. At the moment, I'm not able to reproduce this (I have a feeling that this "WebSocket closed unexpectedly" hints at a server-side issue, which seems to be addressed now). Could you give it another try and post your results here?

**Comment by nkgami** [comment]
@raaaar Thank you for comments. I tried again and confirmed that the problem did not occur. Could you tell me some more detail (e.g. cause, duration and affected region) about the "server-side issue" ?

**Comment by raaaar** [comment]
Glad to hear that the issue is resolved. @priyaravi20 would be able to find out the relevant details on the root cause of this?

**Comment by priyaravi20** [comment]
We think this might be related to changes possibly due to some of the traffic routing needed to happen due to hurricanes. Please let us know if you see any outages with a fiddler trace and we can dig deeper.
