### ISSUE TITLE
Latency issue

### ISSUE THREAD

**Issue by PanosPeriorellis** [Azure-Samples/Cognitive-Speech-STT-Android#57]
A customer has raised the following issue regarding performance:

On the Android SDK there is a second delay between firing up the mic ( micClient.startMicAndRecognition() ) and the recording actually happening.  Every subsequent call there is about a 1/3 of a second delay.  

How can we reduce the initial second-long delay?

**Comment by priyaravi20** [comment]
I have filed a request for this and will be making changes with next release.
