### ISSUE TITLE
Getting this -2147418113 error while doing instant recognition

### ISSUE THREAD

**Issue by sunilsunny565** [Azure-Samples/Cognitive-Speech-STT-Android#59]
Not sure what does this error mean -2147418113. After a few successfull recognitions I am getting this error code and then it will not work at all. The same error happens every time.

**Comment by priyaravi20** [comment]
This translates to unexpected input on our side. Does the same file work a few times and then stop working or reco stops working midway?Can you send us a trace to look into further?

**Comment by sunilsunny565** [comment]
This issue happens when we start a new recognition, this error code is thrown even before we try to say something. This issue never happened in the midway of recognition. Ones recognition start without this error eveything goes smoothly as expected. I don't know how to trace this issue, is the logcat log will do?

**Comment by raaaar** [comment]
Unfortunately, the error code is completely meaningless (it roughly translates to "something went south someplace"). It could be mic, could be the connection to the service, could be something else. If you can share the log that'd be a start. Fiddler trace would also be a great help.

**Comment by sunilsunny565** [comment]
I think I found the issue, this is happening when I am initializing `micClient` to `null `after each recognition along with  `this.micClient.endMicAndRecognition();`. If I am maintianing a singleton object of  `micClient` then this issue is not happening. So the reason is calling  ```
 this.micClient = SpeechRecognitionServiceFactory.createMicrophoneClient(
                            this,
                            this.getMode(),
                            this.getDefaultLocale(),
                            this,
                            this.getPrimaryKey());
```
for each recogintion.

**Comment by raaaar** [comment]
So, if I understand correctly, you never properly disposed of the old micClient, so it remained in a limbo state until the next GC cycle. So, whenever the new client would be created before the old one is garbage-collected, it would fail acquiring the mic. Is this correct?

**Comment by sunilsunny565** [comment]
So what is the proper way of disposing old micClient ?.
```
public void onFinalResponseReceived(final RecognitionResult response) {
 if (micClient != null) {
            micClient.endMicAndRecognition();
            micClient = null;
        }
}
```
I was doing this each time after recognition is completed. Which I thought was proper disposal ?. Anyway if I am commenting this line  `micClient = null;` there are no issues since 
```
if (micClient == null) {
            startVoiceRecorder();
            onBeginningOfSpeech();
            micClient = SpeechRecognitionServiceFactory.createMicrophoneClient(
                    getActivity(),
                    getMode(),
                    getLocale(),
                    iSpeechRecognitionServerEvents,
                    getPrimaryKey());
            micClient.setAuthenticationUri(getAuthenticationUri());
        }
        micClient.startMicAndRecognition();
```
this code will not create a new `micClient` but for me the issue is I have recognition in different languages so I have to change the `getLocale()` and hence need to create a new micClient with the new language locale.

**Comment by raaaar** [comment]
In addition to `endMicAndRecognition`, the [sample also calls `finalize`](https://github.com/Azure-Samples/Cognitive-Speech-STT-Android/blob/master/samples/SpeechRecoExample/src/com/microsoft/CognitiveServicesExample/MainActivity.java#L407) on the client before setting it to `null`. Normally, you don't need to force-call finalize, it happens automatically during garbage collection, but if you want/need to reuse the mic right away, you might want to give it a try.

**Comment by raaaar** [comment]
I tried to repro this behavior, but couldn't do it reliably (no matter what I did to abuse the SDK, I've only seen it a couple of times, very sporadically). Closing this for now, if you're still struggling with the issue, please reopen with a quick descriptions of steps needed to reproduce it.

**Comment by sunilsunny565** [comment]
Yes, calling `finalize` seems to fix this issue. but the delay in starting new recognition keep on increasing. So instead of this I have created 2  single instance `micClients` for each language, which seems to be good workaround for me now.
