### ISSUE TITLE
SpeechSDK\bin\SpeechSDK.jar is missing.

### ISSUE THREAD

**Issue by Yash-Kansagara** [Azure-Samples/Cognitive-Speech-STT-Android#8]
This file is mentioned in Get started with Bing Speech Recognition, [here.](https://www.microsoft.com/cognitive-services/en-us/speech-api/documentation/getstarted/getstartedjavaandroid#Prerequisites)

file SpeechSDL.jar which is available [here](https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Speech/SpeechToText/Android/SpeechSDK/bin/SpeechSDK.jar) is missing.

**Comment by priyaravi20** [comment]
Please run gradle to pull the jar file.
